// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/_hub/**:feature': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.8.23_db0@0.3.1_ioredis@5.6.0_magicast@0.3.5_vite@6.2.4_jiti@2.4.2_light_c4f9958ba1b0f94e3a0fad04c78a9a9e/node_modules/@nuxthub/core/dist/runtime/base/server/api/_hub/[...feature]').default>>>>
    }
    '/api/_hub': {
      'head': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.8.23_db0@0.3.1_ioredis@5.6.0_magicast@0.3.5_vite@6.2.4_jiti@2.4.2_light_c4f9958ba1b0f94e3a0fad04c78a9a9e/node_modules/@nuxthub/core/dist/runtime/base/server/api/_hub/index.head').default>>>>
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.8.23_db0@0.3.1_ioredis@5.6.0_magicast@0.3.5_vite@6.2.4_jiti@2.4.2_light_c4f9958ba1b0f94e3a0fad04c78a9a9e/node_modules/@nuxthub/core/dist/runtime/cors.dev').default>>>>
    }
    '/api/_hub/manifest': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.8.23_db0@0.3.1_ioredis@5.6.0_magicast@0.3.5_vite@6.2.4_jiti@2.4.2_light_c4f9958ba1b0f94e3a0fad04c78a9a9e/node_modules/@nuxthub/core/dist/runtime/base/server/api/_hub/manifest.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt@3.16.2_@parcel+watcher@2.5.1_db0@0.3.1_eslint@9.23.0_jiti@2.4.2__ioredis@5.6.0_lig_bc126578987761a04c289f44ea3722a5/node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+icon@1.11.0_magicast@0.3.5_vite@6.2.4_jiti@2.4.2_lightningcss@1.29.2_terser@5.39._290b4bfafac8c2ab4b124d0c06af63ad/node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/_ipx/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+image@1.10.0_db0@0.3.1_ioredis@5.6.0_magicast@0.3.5/node_modules/@nuxt/image/dist/runtime/ipx').default>>>>
    }
  }
}
export {}